#pragma once

#define _SIZE(WIDTH, HEIGHT) ((WIDTH) * (HEIGHT))
#define SIZE(NAME) _SIZE(NAME##_WIDTH, NAME##_HEIGHT)

#define SECTOR_LENGTH 2048

#define VRAM_WIDTH  1024
#define VRAM_HEIGHT  512

#define BATTLESCENE_PALETTE_WIDTH   16
#define BATTLESCENE_PALETTE_HEIGHT  16

#define BATTLESCENE_TEXTURE_WIDTH  256
#define BATTLESCENE_TEXTURE_HEIGHT 256

#define BATTLESCENE_CELL_WIDTH     128
#define BATTLESCENE_CELL_HEIGHT    256
